language: generic
sudo: required
env: SWIFT_VERSION=5.2.4

matrix:
  include:
    - os: linux
      dist: focal
    - os: osx
      osx_image: xcode11

install: 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update && sudo apt-get install
          binutils
          git
          gnupg2
          libc6-dev
          libcurl4
          libedit2
          libgcc-9-dev
          libpython2.7
          libsqlite3-0
          libstdc++-9-dev
          libxml2
          libz3-dev
          pkg-config
          tzdata
          zlib1g-dev;
    fi;

  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)" 

script:
  - swift test
